services:
  fedow_django:
#    image: tibillet/fedow:alpha1
    build: .
    container_name: fedow_django
    hostname: fedow_django
    restart: always
    env_file: .env
    user: fedow
    volumes:
      - ./ssh:/home/fedow/.ssh
      - ./:/home/fedow/Fedow
    networks:
      - fedow_backend
    command: "bash start.sh"

  fedow_nginx:
    image: nginx
    restart: always
    container_name: fedow_nginx
    hostname: fedow_nginx
    volumes:
      - ./www:/www
      - ./logs:/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fedow_django
    links:
      - fedow_django:fedow_django
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.fedow_nginx.tls.certresolver=myresolver
      - traefik.http.routers.fedow_nginx.rule=Host(`$DOMAIN`)
    networks:
      - frontend
      - fedow_backend


networks:
  frontend:
    external: true
  fedow_backend:
