version: '3'
services:
  fedow:
    image: tibillet/fedow:alpha1
    hostname: fedow
    container_name: fedow
    env_file: .env
    user: fedow
    restart: unless-stopped
    ports:
      - 8442:80
    volumes:
      - ./:/home/fedow/Fedow
