services:
  fedow_memcached:
    image: memcached:1.6
    container_name: fedow_memcached
    hostname: fedow_memcached
    restart: always
    networks:
      - fedow_backend

  fedow_django:
#    image: tibillet/fedow:alpha1
    build: .
    container_name: fedow_django
    hostname: fedow_django
    restart: always
    env_file: .env
    user: fedow
    links:
      - fedow_memcached:memcached
    volumes:
      - ./ssh:/home/fedow/.ssh
      - ./:/home/fedow/Fedow
      - fedow_database:/home/fedow/Fedow/database
    networks:
      - fedow_backend
    # For production :
#    command: "bash start.sh"
    # For dev :
    command: "bash start_dev.sh"

    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "demo.tibillet.localhost:172.17.0.1"
      - "billetistan.tibillet.localhost:172.17.0.1"
      - "cashless.tibillet.localhost:172.17.0.1"


  fedow_nginx:
    image: nginx
    restart: always
    container_name: fedow_nginx
    hostname: fedow_nginx
    volumes:
      - ./www:/www
      - ./logs:/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fedow_django
    links:
      - fedow_django:fedow_django
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.fedow_nginx.tls.certresolver=myresolver
      - traefik.http.routers.fedow_nginx.rule=Host(`$DOMAIN`)
      - traefik.http.services.fedow_nginx.loadbalancer.server.port=80

    networks:
      - frontend
      - fedow_backend


volumes:
  fedow_database:

networks:
  frontend:
    external: true
  fedow_backend:


# docker build -t fedow . && docker tag fedow tibillet/fedow:latest && docker tag fedow tibillet/fedow:0.9.2 && docker push tibillet/fedow:latest && docker push tibillet/fedow:0.9.2