version: '3'
services:
  fedow:
    hostname: fedow
    container_name: fedow
    build: .
    env_file: .env
    user: fedow
    restart: unless-stopped
    volumes:
      - "./:/fedow"
      - "./bashrc:/home/fedow/.bashrc"
    working_dir: /fedow
    command: "bash ./launcher_test.sh"
#    command: "sleep infinity"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fedow.rule=Host(`fedow.traefik.me`)"
      - "traefik.http.routers.fedow-tls.tls.domains[0].main=fedow.traefik.me"
      - "traefik.http.routers.fedow-tls.tls.domains[0].sans=fedow-*.traefik.me"

